import Head from 'next/head';
import Image from 'next/image';

import Navbar from '../components/Navbar';
import storefront from '../assets/storefront.jpeg';

export default function About() {
	return (
		<>
			<Head>
				<title>Game's - About</title>
				<meta name="description" content="Generated by create next app" />
				<script src="https://cdn.tailwindcss.com"></script>
			</Head>

			<div>
        <Navbar />
				<div className="absolute inset-x-0 top-0 z-10 origin-top-right transform p-2 transition md:hidden">
					<div className="overflow-hidden rounded-lg bg-white shadow-md ring-1 ring-black ring-opacity-5">
						<div className="flex items-center justify-between px-5 pt-4">
							<div className="text-xl font-medium">Game's Farmers Market</div>
							<div>
								<button
									type="button"
									className="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-green-600"
								>
									<span className="sr-only">Close main menu</span>

									<svg
										className="h-6 w-6"
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke-width="1.5"
										stroke="currentColor"
										aria-hidden="true"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="M6 18L18 6M6 6l12 12"
										/>
									</svg>
								</button>
							</div>
						</div>
						<div className="space-y-1 px-2 pt-2 pb-3">
							<a
								href="/about"
								className="block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900"
							>
								About
							</a>
							<a
								href="/products"
								className="block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900"
							>
								Products
							</a>
							<a
								href="/contact"
								className="block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900"
							>
								Contact
							</a>
						</div>
					</div>
				</div>
			</div>

			<main className="p-4 mt-8 mx-0 sm:mx-4 mb-4 sm:mb-8 bg-red-700 rounded-0 sm:rounded-3xl">
				<h1 className="p-12 text-3xl font-bold text-center tracking-tight text-white sm:text-4xl md:text-5xl">
					History of Earl Game and Games Market
				</h1>
				<div className="flex w-full mb-4">
					<Image
						className="w-3/4 sm:w-1/2 mx-auto rounded-3xl border-white border-2"
						src={storefront}
						alt="Owner"
						height={800}
						width={800}
					/>
				</div>
				<p className="m-6 p-6 indent-10 text-lg bg-white rounded-3xl">
					{`Games Market has been owned and operated by Earl Game since 1972. Earl has worked in the grocery business most of his life, starting by supporting himself at the age of 12. His family was forced to split as a result of the death of his mother and the impossible demands on his father, trying to raise a large family by himself during the depression. In his early 20's (1940's) he married Peggy and moved to Newport News. For a short period of time he worked in the shipyard, but quickly gravitated back to the grocery business, to what would be his life's work.`}
				</p>

				<p className="m-6 p-6 indent-10 text-lg bg-white rounded-3xl">
					{`He began working in the meat department at the A&P store and eventually moved to midtown Newport News in the summer of 1958 to run the meat department when the Beaconsdale A&P opened.
          In the 60's Earl moved to the commissary at Langley Field and ran the meat department. He also served as Assistant Manager of the commissary into the 70's. In 1972, Earl bought what was then "Grimes" and renamed it Farmer's Market. At that point he owned the store with Al Hatfield, a peer of his in the grocery business for about 20 years, but within a few years of working in partnership, the two decided that Earl would buy Al's part of the business and go on his own.`}
				</p>

				<p className="m-6 p-6 indent-10 text-lg bg-white rounded-3xl">
					{`Over the last 35 years, Earl Game has operated as an independent
					grocer on that spot, gaining a reputation for being an honest and
					reputable businessman in the community. Through the years he has
					established the Game's Farmers Market as a store with a friendly
					country atmosphere, specializing in meat, his area of expertise. In
					2007, the store was completely destroyed by fire, but at the age of
					78, Earl purposed to rebuild the store better than ever. He did. Earl
					passed away on March 2, 2010, able to see the reconstruction of the
					store as a culmination of his life's work and very satisfied with the
					accomplishment before his death. The business is now being run by the
					family with a continued commitment to the excellence Earl created.`}
				</p>
			</main>
		</>
	);
}
