import Head from 'next/head';
import Image from 'next/image';
import { GiHamburgerMenu } from 'react-icons/gi';

import storefront from '../assets/gfm.jpeg';
import produce from '../assets/produce.jpeg';

export default function Home() {
	return (
		<div className="font-sans">
			<Head>
				<title>Game's Farmers Market</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<script src="https://cdn.tailwindcss.com"></script>
			</Head>

			<div className="relative overflow-hidden bg-white">
				<div className="mx-auto max-w-7xl">
					<div className="relative z-10 bg-white pb-8 sm:pb-16 md:pb-20 lg:w-full lg:max-w-2xl lg:pb-28 xl:pb-32">
						{/* Slant shape */}
						<svg
							className="absolute inset-y-0 right-0 hidden h-full w-48 translate-x-1/2 transform text-white lg:block"
							fill="currentColor"
							viewBox="0 0 100 100"
							preserveAspectRatio="none"
							aria-hidden="true"
						>
							<polygon points="50,0 100,0 50,100 0,100" />
						</svg>

						<div>
							<div className="relative px-4 pt-6 sm:px-6 lg:px-8">
								<nav
									className="relative flex items-center justify-between sm:h-10"
									aria-label="Global"
								>
									<div className="flex flex-shrink-0 flex-grow items-center lg:flex-grow-0">
										<div className="flex w-full items-center justify-between md:w-auto">
											<a href="#" className='text-4xl'>
												<span className="sr-only">Your Company</span>
												Game's Farmers Market
											</a>
											<div className="-mr-2 flex items-center md:hidden">
												<button
													type="button"
													className="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
													aria-expanded="false"
												>
													<span className="sr-only">Open main menu</span>

													<svg
														className="h-6 w-6"
														xmlns="http://www.w3.org/2000/svg"
														fill="none"
														viewBox="0 0 24 24"
														stroke-width="1.5"
														stroke="currentColor"
														aria-hidden="true"
													>
														<path
															stroke-linecap="round"
															stroke-linejoin="round"
															d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
														/>
													</svg>
												</button>
											</div>
										</div>
									</div>
									<div className="hidden md:ml-10 md:block md:space-x-8 md:pr-4">
										<a
											href="#"
											className="font-medium text-gray-500 hover:text-gray-900"
										>
											About
										</a>
										<a
											href="#"
											className="font-medium text-gray-500 hover:text-gray-900"
										>
											Products
										</a>
										<a
											href="#"
											className="font-medium text-gray-500 hover:text-gray-900"
										>
											Contact
										</a>
									</div>
								</nav>
							</div>
							<div className="absolute inset-x-0 top-0 z-10 origin-top-right transform p-2 transition md:hidden">
								<div className="overflow-hidden rounded-lg bg-white shadow-md ring-1 ring-black ring-opacity-5">
									<div className="flex items-center justify-between px-5 pt-4">
										<div className='text-xl font-medium'>
											Game's Farmers Market
										</div>
										<div>
											<button
												type="button"
												className="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
											>
												<span className="sr-only">Close main menu</span>

												<svg
													className="h-6 w-6"
													xmlns="http://www.w3.org/2000/svg"
													fill="none"
													viewBox="0 0 24 24"
													stroke-width="1.5"
													stroke="currentColor"
													aria-hidden="true"
												>
													<path
														stroke-linecap="round"
														stroke-linejoin="round"
														d="M6 18L18 6M6 6l12 12"
													/>
												</svg>
											</button>
										</div>
									</div>
									<div className="space-y-1 px-2 pt-2 pb-3">
										<a
											href="#"
											className="block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900"
										>
											About
										</a>
										<a
											href="#"
											className="block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900"
										>
											Products
										</a>
										<a
											href="#"
											className="block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900"
										>
											Contact
										</a>
									</div>
								</div>
							</div>
						</div>

						<main className="mx-auto mt-10 max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
							<div className="sm:text-center lg:text-left">
								<h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
									<span className="block xl:inline">Committed to serving</span>
									<span className="block mx-2 text-green-600 xl:inline">
										you.
									</span>
								</h1>
								<p className="mt-3 text-base text-gray-500 sm:mx-auto sm:mt-5 sm:max-w-xl sm:text-lg md:mt-5 md:text-xl lg:mx-0">
									Serving the community since 1972, Game's Farmers Market provides produce, meat products, and Amish goods at the best price in Hampton Roads.
								</p>
							</div>
						</main>
					</div>
				</div>
				<div className="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
					<Image
						className="h-56 w-full object-cover sm:h-72 md:h-96 lg:h-full lg:w-full"
            src={produce}
						alt="produce"
            height={1000}
            width={1000}
					/>
				</div>
			</div>
		</div>
	);
}
